/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "sli_bt_gattdb_def.h"

extern const sli_bt_gattdb_t gattdb;

#define gattdb_generic_attribute              1
#define gattdb_service_changed_char           3
#define gattdb_database_hash                  6
#define gattdb_client_support_features        8
#define gattdb_device_name                    11
#define gattdb_device_information             14
#define gattdb_manufacturer_name_string       16
#define gattdb_system_id                      18
#define gattdb_voltage_monitor                19
#define gattdb_air_temperature_data           21
#define gattdb_ambient_light                  24
#define gattdb_dc_voltage                     26
#define gattdb_ware_temperature               29
#define gattdb_cdc                            32
#define gattdb_die_temperature                35
#define gattdb_vac                            38
#define gattdb_air_logs                       41
#define gattdb_dc_volt_logs                   44
#define gattdb_ware_temp_logs                 47
#define gattdb_cdc_logs                       50
#define gattdb_peak_count_logs                53
#define gattdb_vac_logs                       56
#define gattdb_count_seconds                  59
#define gattdb_log_count                      62
#define gattdb_led_color                      65
#define gattdb_firmware_version               68
#define gattdb_battery_max                    71
#define gattdb_die_temp_max                   74
#define gattdb_battery_percent                77
#define gattdb_automation_io                  78
#define gattdb_arm                            80
#define gattdb_interzone_timeout              82
#define gattdb_set_voltage_trigger            84
#define gattdb_enable_trigger                 86
#define gattdb_output_toggle                  88
#define gattdb_peak_seconds                   90
#define gattdb_threshold_count                92
#define gattdb_color_variant                  94
#define gattdb_cdc_max_logs                   96
#define gattdb_timer                          99
#define gattdb_memory_test                    101
#define gattdb_color_test                     103
#define gattdb_reset                          105
#define gattdb_null_dc_current                107
#define gattdb_data_runs                      109
#define gattdb_peak_liq_temp                  111
#define gattdb_peak_ware_temp                 113
#define gattdb_peak_dc_volt                   115
#define gattdb_peak_ac_volt                   117
#define gattdb_vxkey                          119
#define gattdb_peak_second_8                  121
#define gattdb_error_logs                     123
#define gattdb_vdd                            125
#define gattdb_calibration                    127
#define gattdb_mac                            129
#define gattdb_alit_threshold                 131
#define gattdb_tbat                           133
#define gattdb_alit_val                       135
#define gattdb_timestamp                      137
#define gattdb_ota                            138
#define gattdb_ota_control                    140


#endif // __GATT_DB_H
